name: Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo Hello, world!
      - name: Publish
        run: echo Hello, world!
  test:
    name: Deploy to Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Hello, world!
  e2e:
    name: Run e2e tests
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: echo Hello, world!
  prod:
    name: Deploy to Production
    needs: e2e
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy
        run: echo Hello, world!
      - name: Tag Release
        run: echo Hello, world!
      - name: Rollback
        run: echo Hello, world!
